### ISSUE TITLE
demo page is broken

### ISSUE THREAD

**Issue by rbeier** [ailon/markerjs#1]
Hi, the demos on your [homepage](https://markerjs.com/) is not working for me at the moment.

That's the problem:
```
Uncaught ReferenceError: markerjs is not defined
    at showMarkerJs ((index):46)
    at HTMLImageElement.onclick ((index):152)
```

I'm using chrome 71 on a mac.

**Comment by ailon** [comment]
Just tried in Chrome 71 (on Windows though) and it works for me. Judging by the error it looks like JavaScript just failed to load. Can you please try reloading and if that doesn't help, could you please take a look at what's going on in the Network tab of Chrome's DevTools? 

Thanks!

**Comment by rbeier** [comment]
It looks like https://unpkg.com/markerjs@1.1.1/index.js could not be found. It returns a 404. 

![image](https://user-images.githubusercontent.com/12234796/50333633-452c8900-0506-11e9-8dc2-4132ca6d0e2b.png)

**Comment by ailon** [comment]
Hmm... index.js is not the file it should be getting. Do you by any chance have some Chrome extension that may affect this (trying to figure out what "this" could be as I imagined picking which file to serve should've happened on the unpkg.com side).

**Comment by rbeier** [comment]
I opened the page again in the guest mode of Chrome, there the same error occurs.

Btw. I have the same problem in Safari.

**Comment by ailon** [comment]
What happens if you just open https://unpkg.com/markerjs

**Comment by rbeier** [comment]
I get redirected to https://unpkg.com/markerjs@1.1.1/index.js 🤔

**Comment by ailon** [comment]
That's odd. I'm out of ideas for now, so I updated the page to reference the correct js file directly (though not hardcoding the version). Can you please try refreshing the page on https://markerjs.com and see if it works for you now?

**Comment by rbeier** [comment]
now it works :)
