### ISSUE TITLE
Can you change the font face, color, size?

### ISSUE THREAD

**Issue by cviewsupport** [ailon/markerjs#11]
Hello, this more of a question than an issue but I could not find a phone number, web form or email address on the website.

We are looking to build a web app that lets pastors create sermon slides / graphics on the web for free.  They basically need to be able to add text to images and save them.

They need to be able to select from many font types.
Is this possible with markerjs?

**Comment by ailon** [comment]
Hi there. There's an email address under Contact us right at the bottom of the page ;) It's info@markerjs.com

No, there's no way to change fonts right now. The library is meant for image annotation and not as an image editor so I'm not sure I'd want to include user-facing font selection in the future either. I may consider adding an option to set a different font from code but I guess this is not what you are after.

Alan.
