### ISSUE TITLE
show() returns i.target.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by gitanupam** [ailon/markerjs#13]
`show()` returns `i.target.getBoundingClientRect is not a function`

Have been playing with it for a while now but couldn't really see what could I be doing wrong. This is just out of the box.

```
var mark = new markerjs.MarkerArea($("#cropper_image"));

  mark.show(function(dataUrl) {
    console.log(dataUrl)
      // var res = $("#cropper_result_image");
      // res.src = dataUrl;
  });
```

**Update:**  Ah, figured that it works if I don't use JQuery. Does the library not work with jQuery?

**Comment by ailon** [comment]
It shouldn't be a problem to use it with jQuery in general. At least I don't see why it would be. markerjs.com uses Bootstrap which uses jQuery and it works fine there. I'm a little rusty on jQuery ;) but I think what `$("#cropper_image")` returns is not a pure HTML object but rather some jQuery wrapper and that's probably an issue here - you need to pass a reference to a DOM object to `MarkerArea()`.
