### ISSUE TITLE
Event delegate events

### ISSUE THREAD

**Issue by philip-firstorder** [ailon/markerjs#16]
**Problem**
By attaching events both on MarkerArea & Markers & Grips the performance of the move/resize functions decreases a lot.

Here is how many events are currently attached:
**MarkerArea**: mousedown, mouseup, mousemove
**MarkerBase**: mousedown, mouseup, mousemove, touchstart, touchend, touchmove
**Grip**: mousedown, mouseup, mousemove, touchstart, touchend, touchmove

For example if you have 100 rectangles you end up with 3 + 600 + 8*600 = 5.403 event listeners.
If you also have 100 images, each with 100 rectangles you end up with 54.030 event listeners.

**How to reproduce**
Draw 2 rectangles next to each other.
Grab to resize on rectangle so that it overlaps the other one.
If you move the mouse fast enough the resize event eventually stops triggering.

**Solution**
Refactor the code so that you only capture the events on the entire document ONCE.
This way you should only have 6 events no matter how many elements you draw in the DOM.

```ts
// Call this on when the first MarkerArea is initialised
document.addEventListener("mousedown", this.mouseDown);

private mouseDown = (e: MouseEvent) => {
  if (e.target && e.target.matches("markerjs-control-grip")) {
    console.log("Grip mouseDown!");
  }
});

// Call this if you implement a destroy function after the last MarkerArea is removed
document.removeEventListener("mousedown", this.mouseDown);
```

See here details on the technique
https://davidwalsh.name/event-delegate

**Comment by ailon** [comment]
I totally agree that resizing inaccuracy and similar issues should be fixed. I'll look into it.

Having said that, I don't think performance with 100 simultaneously annotated images with 100 markers each is a scenario marker.js should be tailored to. We are not building an Adobe Illustrator competitor here ;)

My totally non-scientific view of a typical use case is up to 10-20 markers on an approximately 1.03 annotated image at a time.

So these are two unrelated issues (or at least not one and the same issue). I will close this one but keep #15 open until it's fixed.

**Comment by philip-firstorder** [comment]
Biggest problem I solved was by commenting the mousemove listener on the marker/grip, this way only the markerArea mousemove listener is active.  Resizing and Dragging then works without interruptions.
