### ISSUE TITLE
Unable to get property 'clientWidth' of undefined or null reference

### ISSUE THREAD

**Issue by mobile-g** [ailon/markerjs#2]
When running this in a Win10 app I get the below error (before Win10 crashes :( )

Unable to get property 'clientWidth' of undefined or null reference

In a normal browser it works fine.

**Comment by Dari4sho** [comment]
This pops up when the element does not exist the moment `new MarkerArea(document.getElementById('myImage'))` gets called

**Comment by ailon** [comment]
May be resolved in v1.2 by passing a different `targetRoot` via `config`
