### ISSUE TITLE
Line/Arrow state should only have x1, y1, x2, y2

### ISSUE THREAD

**Issue by philip-firstorder** [ailon/markerjs#20]
Line and Arrow markers should probably not inherit from Rect Marker.

```json
{
  "markers": [
    {
      "x1": 0,
      "y1": 0,
      "x2": 200,
      "y2": 0,
      "markerType": "LineMarker",
      "width": 200,
      "height": 50,
      "translateX": 109.5,
      "translateY": 212.5
    },
    {
      "x1": 0,
      "y1": 0,
      "x2": 200,
      "y2": 0,
      "markerType": "ArrowMarker",
      "width": 200,
      "height": 50,
      "translateX": 109.5,
      "translateY": 212.5
    }
  ]
}
```

**Comment by ailon** [comment]
Hmm.. `LineMarkerBase` and `LineMarkerBaseState` both extend corresponding `MarkerBase` classes/interfaces which have all those "extras". I didn't check if there's a real reason to save those out but I think it's consistent this way and probably doesn't introduce any issues (except for a few extra bytes). So I'm inclined to just keep it as-is for the time being.
