### ISSUE TITLE
Multi session markers error

### ISSUE THREAD

**Issue by mcjackson18** [ailon/markerjs#24]
After loading in markers using `previousState`, some of the marker types give an error when editing.

For example, lines and arrows - when an arrow is loaded from a previous session and you click on a dot to change the length, either the tip of the arrow jumps off the image or gives the  following error:

```
Error: <line> attribute y1: Expected length, "0-93".
markerjs.umd.js:15 Uncaught TypeError: Failed to execute 'setTranslate' on 'SVGTransform': The provided float value is non-finite.
    at e.positionGrip (markerjs.umd.js:15)
    at e.positionGrips (markerjs.umd.js:15)
    at e.adjustControlBox (markerjs.umd.js:15)
    at e.resize (markerjs.umd.js:15)
    at e.manipulate (markerjs.umd.js:15)
    at SVGSVGElement.G.mouseMove (markerjs.umd.js:15)
```

**Comment by ailon** [comment]
Hi Mark,

Are you experiencing this in your own project or on markerjs.com demo as well? (look for "continuous annotation" example). I can't recreate this issue there. If it works for you there as well, would it be possible for you to create some simple repro where the issue manifests itself?

Thanks!

**Comment by mcjackson18** [comment]
@ailon, thanks for the quick response, I've managed to resolve the issue.
