### ISSUE TITLE
Can marker.js be extended to annotate text?

### ISSUE THREAD

**Issue by aitoehigie** [ailon/markerjs#34]
Can marker.js be extended to annotate text? My TypeScript knowledge is very weak but I will appreaciate if given tips on where to look in the codebase.
Kind regards

**Comment by ailon** [comment]
I don't think it's technically possible to render an arbitrary DOM element to an image to annotate with marker.js. Just annotating as some notes linked to the page elements or something like that is out of marker.js scope and I think there are other libraries for that.
