### ISSUE TITLE
Marker.js email not working

### ISSUE THREAD

**Issue by fatfrog** [ailon/markerjs#4]
Hi,

I tried emailing you about buying a license but the email bounced?  Is there another way to contact you?

`

Message not deliveredThere was a problem delivering your message to info@markerjs.com. See the technical details below.LEARN MORE | Message not deliveredThere was a problem delivering your message to info@markerjs.com. See the technical details below.LEARN MORE | Message not delivered | There was a problem delivering your message to info@markerjs.com. See the technical details below. | LEARN MORE
-- | -- | -- | -- | --
Message not deliveredThere was a problem delivering your message to info@markerjs.com. See the technical details below.LEARN MORE | Message not delivered | There was a problem delivering your message to info@markerjs.com. See the technical details below. | LEARN MORE
Message not delivered
There was a problem delivering your message to info@markerjs.com. See the technical details below.
LEARN MORE
The response was:The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 [markerjs.com 104.198.14.52: timed out]

`

**Comment by ailon** [comment]
Sorry about that and thank you for the heads up! I will fix this.

In the meantime, you can email me at ailon@ailon.org

**Comment by fatfrog** [comment]
Thanks for the quick response, I will be in touch!
