### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by Maria-Fernandes52** [ailon/markerjs#5]
markerjs.esm.js:732 Uncaught TypeError: Cannot read property 'style' of undefined
    at Object.positionToolbar (markerjs.esm.js:732)
    at Object.positionUI (markerjs.esm.js:728)
    at adjustUI (markerjs.esm.js:722)

On drawing the bounding box and resizing the browser

**Comment by imRish** [comment]
I am getting this as well. Any solutions or workaround?

**Comment by ailon** [comment]
Hi,

Could you please be more specific? I tried resizing the browser with editor active on markerjs.com and didn't get any errors. Any specific steps to reproduce this would help.

Thanks!

Alan.

**Comment by imRish** [comment]
Hey, sorry for late response.

So I am using this with an electron project. 

This is the calling code.
`var mark = new MarkerArea(img);
mark.open();
return mark;`

And following is the error.

`Uncaught TypeError: Cannot read property 'style' of undefined
    at V.positionToolbar (/Users/rish/code/js/zenshot/node_modules/markerjs/markerjs.umd.js:1)
    at V.positionUI (/Users/rish/code/js/zenshot/node_modules/markerjs/markerjs.umd.js:1)
    at V.adjustUI (/Users/rish/code/js/zenshot/node_modules/markerjs/markerjs.umd.js:1)`

Resizing the window generates more of this error.

**Comment by ailon** [comment]
Thanks, @imRish! I was able to replicate it now as it only happens when the built-in toolbar isn't used (`mark.open()` vs. `mark.show()`)

I will investigate and fix this within next couple of days.

**Comment by imRish** [comment]
Sounds great! If you can explain a bit about "where to start", I'll be happy to try and submit a PR.

**Comment by ailon** [comment]
Sorry it took longer than it had to (been busy with other things) but it should be fixed now.
