### ISSUE TITLE
is there any way i can create custom buttons for markers, instead of default design?

### ISSUE THREAD

**Issue by vipulkanhasoft** [ailon/markerjs#54]
Hello, I need to design custom buttons and ui, i just need events that will do same when i click on the marker on top.
Basically i have to create my own Toolbar.

**Comment by ailon** [comment]
Hi,

You can hide the toolbar and/or toolbox (marker property panels) using:
```
markerArea.uiStyleSettings.hideToolbar = true;
markerArea.uiStyleSettings.hideToolbox = true;
```
See 
https://markerjs.com/reference/interfaces/istylesettings.html#hidetoolbar
https://markerjs.com/reference/interfaces/istylesettings.html#hidetoolbox

And then you can add new markers from your code using `MarkerArea.createNewMarker()` https://markerjs.com/reference/classes/markerarea.html#createnewmarker

Setting various marker properties (color, line width, etc.) from code is not easy though. So if you need those options you may consider hiding just the toolbar and keeping the toolbox.
