### ISSUE TITLE
markerArea.toolbar.setSelectMode() does not work

### ISSUE THREAD

**Issue by JamMaster1999** [ailon/markerjs#57]
Hello,
I have an issue with using .toolbar.setSelectMode(). After calling it, though it successfully switches the toolbar icon to "select" button, the actual functionality is still stuck on whatever marker which was previously selected. Simply put, the function appears to be only visually activate the "select" button, not functionally. 

Thanks for the great library

**Comment by ailon** [comment]
This method kinda does what it says it does ;) It switches the button on a toolbar but doesn't actually change the mode of the `MarkerArea`

For that use `MarkerArea.setCurrentMarker()`
https://markerjs.com/reference/classes/markerarea.html#setcurrentmarker

If you call it without the argument it will unselect the currently selected marker and switch to the select mode (including the toolbar button).
