### ISSUE TITLE
iOS 12- WebView Editor is not responding

### ISSUE THREAD

**Issue by shaneeshpatel1** [ailon/markerjs#59]
Hello Team,

When open editor in iOS 12 webview, Editor is freeze and no any features of editor is responding or working.

Please provide the solutions.

Regards,
Shaneesh Patel

**Comment by ailon** [comment]
Unfortunately, marker.js doesn't work on iOS 12 and older. You need iOS 13 or newer.

**Comment by shaneeshpatel1** [comment]
Thanks you @ailon for quick response.
