### ISSUE TITLE
Unable to access tools on mobile

### ISSUE THREAD

**Issue by jasondripjobs** [ailon/markerjs#62]
When using the library in a popup on mobile devices (only tested on iOS Safari and Firefox).

Things seem to work fine until you choose the text tool and they mobile keyboard slides into view.

After the keyboard is gone, there's no way to scroll back or access the top toolbar to save/close the image.

This is what it looks like after the keyboard closes.

![Image from iOS](https://user-images.githubusercontent.com/93935943/160618012-53a9f1bc-b6dc-4b25-a15f-9b6f2f0a009c.png)

**Comment by ailon** [comment]
Hi there. Just tried it in Safari and I was able to scroll it back into place with a two fingers gesture.

**Comment by jasondripjobs** [comment]
Thank you so much! This works on Safari and Firefox mobile.
