### ISSUE TITLE
Add EllipseMarker as a supported marker type

### ISSUE THREAD

**Issue by imsville** [ailon/markerjs#9]
Visually, I think it would be great to have the option of an ellipsis so you could have the option of a circle or ellipsis as markup.  

I understand that this is a more qualitative feature request, but I think that it really add to markerjs!

**Comment by ailon** [comment]
This is now available in version 1.3. Thank you for motivating me, @imsville ;)

**Comment by imsville** [comment]
You're welcome! Thank YOU!
